// <auto-generated />
using AspnetCoreHybridCacheK6.Api;
using AspnetCoreHybridCacheK6.Api.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(WideWorldImportersContext), typeof(WideWorldImportersContextModel))]
