// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AspnetCoreHybridCacheK6.Api
{
    public partial class WideWorldImportersContextModel
    {
        private WideWorldImportersContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8cdefc60-d64e-4650-8f65-9e299ab8a69f"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var order = OrderEntityType.Create(this);
            var orderLine = OrderLineEntityType.Create(this);

            OrderLineEntityType.CreateForeignKey1(orderLine, order);

            OrderEntityType.CreateAnnotations(order);
            OrderLineEntityType.CreateAnnotations(orderLine);

            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
